#!/usr/bin/env python3

import json
import os
import sys

config = json.loads("".join(sys.stdin.readlines()))

if "version" in config:
	version = config["version"]
	
	outputDir = os.path.join(sys.argv[1], "info")
	
	os.makedirs(outputDir, exist_ok=True)
	
	for it in version:
		with open(os.path.join(outputDir, it), "w") as fp:
			print(version[it], file=fp)

print("{}")
